travis:
  secure:
    BINSTAR_TOKEN: l2QKP/+RQ5rQkqZ5aN3tcpzyCInD9wQ1+Og+IPqD2H0iHSU6RnQuszP3cRp9fOy4w7aZuVHbpn8prgw5R5OUhVtFnXjrdEAAAdjMPDCj+XjMC2O69N5Z2UfwMZBpXpKHgSqKQ8iHIcwuXY76DZyDbXQNorRlD7dCm+y9Dy/hiL6Ir3FTx1GuzqFGfJVTOyluitQK/U4H5KZVaVS9cGhRCyk2UGskgE6TIiug1HfdCROmcWdQffTbElbfUtI8OIm2UvYlAZ3Iiw0v592m4GpGLWsj/Dnn/pxeMo2FHi8MgBF9Wc7APLMqObuZyAAcUH/nCxD6RZpgghWSKIeCZPQuUx3zks9CQQa5krZXqtYhlk3QpDeDGh/FvLFjvqJMf9TzOPY8wQL3mwr+CYpLLC4x8jLgGDYfIJ47yusb8PafckF+ltQ6pRXofWUmsVeUHmqQHcBf4tHFkS2iaS5trSh2svkkLQzHK8l5KnaE+EEA4PdJOJhYEVuX3k6ZC5Z3LXJDBT4r6wkIAGaTRBo/C2R2hrcIxr6BeBbp6LLTU/YvJtFmOU3Hp32v7jVzb0HzkoJYpgjSn1umqRyFgURE+jQ0a+uOMLVmq1ghm+E4qCoZwF5OJZqyTANjEoLgmV9/Q0bXSoazofC99fmTTL3NtLa6HEGwuMJmS+P6r59V8VBCEyw=
bot:
  automerge: true
conda_forge_output_validation: true
